server:
  port: 9000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      enabled: true

      metrics:
        # 开启 GatewayMetricsFilter
        enabled: true
#      routes: #在加载的时候会被解析为RouteDefinition对象集合,包含 id,uri,predicate,filters,metadata,order
#      - id: service01 #标识符，区别于其他 Route
#        uri: http://localhost:9001 #路由指向的目的地 uri
#        predicates: #断言，断言为true才转发
#          - Path=/api/service01/**
#        filters: #可对request,response 自定义(重写路径，过滤器)，这里相当于定义了一个filter,放在gateway 的filterChain 中
#          - RewritePath=/api/?(?<segment>.*), /$\{segment}
#          - RequestLog=config
#
#      - id: service02
#        uri: http://localhost:9002
#        predicates:
#          - Path=/api/service02
#        filters:
#          - RewritePath=/api/?(?<segment>.*), /$\{segment}

logging:
  level:
    com.alibaba.nacos: error